name: C++ Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake and build tools
      run: |
        sudo apt-get install -y cmake g++
        cmake --version
        g++ --version

    - name: Build and run tests
      run: |
        cd your_project_directory
        mkdir build
        cd build
        cmake ..
        make
        ./your_test_executable
