name: C++ Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake and build tools
      run: |
        sudo apt-get install -y cmake g++
        cmake --version
        g++ --version

  # your_project_directory = ./ change eet later
  # your_test_executable = ./ change eet later
    - name: Build and run tests
      run: |
        cd googletest 
        mkdir install 
        cd install 
        cmake ../  
        make 
        sudo make install 
        echo "export CPLUS_INCLUDE_PATH=/usr/local/include" >> ~/.bash_profile
        echo "export LIBRARY_PATH=/usr/local/lib" >> ~/.bash_profile
        source ~/.bash_profile 
        g++ -std=c++0x summer.cpp summerMain.cpp -lgtest -lgtest_main -pthread -o sumProgram
        ./sumProgram
