name: C++ Test with Google Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
        cmake --version
        g++ --version

    - name: Download and build Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and run tests
      run: |
        cd $GITHUB_WORKSPACE  # Switch back to the project directory
        mkdir build
        cd build
        cmake ..
        make
        ./tests
