name: C++ Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake and build tools
      run: |
        sudo apt-get install -y  g++

    - name: Build and run tests
      run: |
        g++ -std=c++14 summer.cpp summerMain.cpp -lgtest -lgtest_main -pthread -o sumProgram
        ./sumProgram
